ports = [
  "127.0.0.1:30001:80",
]

[containers.mariadb]
image = "docker.io/library/mariadb:10.7.4"
command = [ '--transaction-isolation=READ-COMMITTED', '--binlog-format=ROW' ]
volumes = [ "./data/nextcloud/mariadb/:/var/lib/mysql/" ]
  [containers.mariadb.env]
  MYSQL_DATABASE = "nextcloud"
  MYSQL_ROOT_PASSWORD = "nextcloud"
  MYSQL_USER = "nextcloud"
  MYSQL_PASSWORD = "nextcloud"

[containers.nextcloud]
image = "docker.io/library/nextcloud:24.0.4"
volumes = [ "./data/nextcloud/nextcloud/:/var/www/html/" ]
  [containers.nextcloud.env]
  NEXTCLOUD_ADMIN_USER = "nichady"
  NEXTCLOUD_ADMIN_PASSWORD = "${PASSWORD}"
  MYSQL_HOST = "127.0.0.1" # nextcloud doesn't like 'localhost'
  MYSQL_DATABASE = "nextcloud"
  MYSQL_USER = "nextcloud"
  MYSQL_PASSWORD = "nextcloud"

